### ISSUE TITLE
New Suppliers Category Filter

### ISSUE THREAD

**Issue by twilkinson099** [Comesto/2-MVP-Dashboard-to-Supplier-Profile#1]
## **Filterable "New Suppliers" Dashboard Discovery**

**Epic Spec:**

**Introduction**
We want buyers to be able to personalise their experience on the dashboard and be able to see product/supplier visuals of relevance to them as quickly as possible. On the product roadmap, we intend to provide this information for the buyer on the back of their choices on our buyer questionnaires.

For the MVP, Paul has suggested a solution whereby we pull "new suppliers" onto the dashboard in a visual card format, and then allow the user to drop-down-filter what they to see by category.

**What problem is this feature request related to?**
When I arrive at the dashboard, I am here to discover new & interesting products that I could not ordinarily find with my wholesaler etc. I expect Comesto to be showing/guiding me to seeing products/suppliers relevant to me and my business as quickly as possible.

**The solution**
Visual "new supplier" cards filterable by category.

**Product Requirements**

1. The supplier cards should be very visual with attractive product imagery.

2. The supplier card should have a header - (supplier name), and a brief description (product type/supplier summary/pitch).

3. Supplier card should be scrollable left to right with a minimum of 3 cards shown (dependent on design size)

4. Ideally, we should be able to track and store what filter options users select.

**Design Requirements**
To be discussed & wireframed - potentially limited to the design features of WP plugins.

**Engineer Requirements**
For Paul Triggs to complete

Database considerations?
Plugin considerations?
External development requirements?
Anticipated timeline?
Technical Debt?

# **Tasks**

- [ ] Wireframe 
- [ ] Paul Triggs to complete engineering requirements (particulaly estimated build time)

**Comment by paul-comesto** [comment]
Tech wise, no problems. There are several ways we can achieve this.

**Comment by paul-comesto** [comment]
Point 4 may be trickier and could be in road map.

**Comment by twilkinson099** [comment]
Point 4 for roadmap

New supplier filter, serves the purpose of allowing a user to find a supplier page of particular interest quickly (as opposed to search and category browse) therefore can we test some of the plug-in options and select one. 

New plugin testing cannot begin until desktop based site complete - due to complete this week.

**Comment by twilkinson099** [comment]
Time estimate: 1/2 day
