### ISSUE TITLE
Product Request

### ISSUE THREAD

**Issue by twilkinson099** [Comesto/2-MVP-Dashboard-to-Supplier-Profile#4]
## **Feature name**

**Epic Spec:**

**Introduction**
This feature is to enable users to request items if they are struggling to find things they want on the platform.

**What problem is this feature request related to?**
I have arrived at Comesto, perhaps as an existing user, and want to use it as a tool to help me find a specific product type. I am disappointed when I can't find it on Comesto and believe they should really have it. 

**The solution**
An input feature to request products.

**Product Requirements**

1. The user should be able to click a button that says something along the lines of "Can't find the product type you're after? Tell us your suggestions".

2. On clicking the button, perhaps a pop up (with the similar format/plugin feature as buyer questionnaires) should arrive with a basic text input field.

**Design Requirements**
To be discussed & wireframed - potentially limited to the design features of WP plugins.

**Engineer Requirements**
For Paul Triggs to complete

Database considerations?
Plugin considerations?
External development requirements?
Anticipated timeline?
Technical Debt?

# **Tasks**

- [ ] Wireframe 
- [ ] Paul Triggs to complete engineering requirements (particulaly estimated build time)

**Comment by paul-comesto** [comment]
All ready built and tested.
